ALTER TABLE `quiz_questions` ADD COLUMN `category` text NOT NULL DEFAULT 'general';
ALTER TABLE `quiz_questions` ADD COLUMN `difficulty` text NOT NULL DEFAULT 'easy';

-- Keep the existing seed question in the general category.

-- 100 original, stable questions: 25 Web3, 25 Web2, 25 calculations, 25 jokes.

-- Web3 fundamentals
INSERT INTO `quiz_questions` (`question`,`options_json`,`correct_option`,`reward_points`,`category`,`difficulty`,`active`) SELECT 'What does blockchain describe?', '["A shared append-only ledger","A private photo folder","A video codec","A keyboard layout]', 0, 40, 'web3', 'easy', 1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does blockchain describe?');
INSERT INTO `quiz_questions` (`question`,`options_json`,`correct_option`,`reward_points`,`category`,`difficulty`,`active`) SELECT 'What is a block usually linked to?', '["The previous block","A browser tab","A printer","A password hint]', 0, 40, 'web3', 'easy', 1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a block usually linked to?');
INSERT INTO `quiz_questions` (`question`,`options_json`,`correct_option`,`reward_points`,`category`,`difficulty`,`active`) SELECT 'What is a wallet seed phrase used for?', '["Recovering wallet control","Compressing images","Naming a token","Measuring gas pressure]', 0, 40, 'web3', 'easy', 1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a wallet seed phrase used for?');
INSERT INTO `quiz_questions` SELECT NULL,'What does a smart contract do?','["Runs programmed rules","Repairs a phone","Prints coins","Stores browser history"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does a smart contract do?');
INSERT INTO `quiz_questions` SELECT NULL,'What does NFT commonly stand for?','["Non-fungible token","New file transfer","Network fee table","Numeric format type"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does NFT commonly stand for?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a fungible item?','["Interchangeable with an equal unit","Always unique","Only digital art","A locked account"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a fungible item?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a public blockchain key commonly used for?','["Receiving or identifying an account","Recovering a secret phrase","Deleting blocks","Changing gravity"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a public blockchain key commonly used for?');
INSERT INTO `quiz_questions` SELECT NULL,'What should never be shared publicly?','["A private key","A public address","A block number","A network name"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What should never be shared publicly?');
INSERT INTO `quiz_questions` SELECT NULL,'What is gas in many blockchain networks?','["A transaction execution fee","A backup password","A type of NFT","A mining keyboard"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is gas in many blockchain networks?');
INSERT INTO `quiz_questions` SELECT NULL,'What is decentralization?', '["Control distributed across participants","One server controls everything","A faster monitor","A type of password"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is decentralization?');
INSERT INTO `quiz_questions` SELECT NULL,'What does a validator help do?', '["Verify and process network activity","Design profile pictures","Write browser plugins","Create passwords"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does a validator help do?');
INSERT INTO `quiz_questions` SELECT NULL,'What is proof of stake based on?', '["Participants locking value to support consensus","Typing speed","Image resolution","Email length"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is proof of stake based on?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a fork in blockchain software?', '["A change that can split or update the rules","A wallet backup","A token logo","A mining cable"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a fork in blockchain software?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a token standard?', '["A shared format and behavior specification","A secret seed","A price prediction","A browser cookie"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a token standard?');
INSERT INTO `quiz_questions` SELECT NULL,'What is on-chain data?', '["Data recorded on a blockchain","Data only in a notebook","A video stream","An offline password"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is on-chain data?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a DAO generally?', '["A community using rules and software to coordinate","A phone charger","A search engine","A private key"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a DAO generally?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a multisignature wallet?', '["A wallet requiring multiple approvals","A wallet with many colors","A wallet without an address","A wallet for photos"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a multisignature wallet?');
INSERT INTO `quiz_questions` SELECT NULL,'What does interoperability mean in Web3?', '["Different systems can work together","A wallet has many passwords","A block has no data","A token has no owner"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does interoperability mean in Web3?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a blockchain explorer?', '["A tool for viewing public chain activity","A game character","A wallet password","A mining machine"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a blockchain explorer?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a layer-2 network designed to do?', '["Process activity with help from a base chain","Replace every wallet","Store passwords","Create jokes"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a layer-2 network designed to do?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a bridge in blockchain ecosystems?', '["A protocol for moving assets or messages between networks","A physical road","A seed phrase","A block reward"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a bridge in blockchain ecosystems?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a cryptographic hash?', '["A fixed-length fingerprint of data","A human username","A transaction fee","A digital painting"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a cryptographic hash?');
INSERT INTO `quiz_questions` SELECT NULL,'Why are confirmed blockchain records difficult to alter?', '["Changing them would require changing linked consensus data","They are printed on paper","They are stored in browsers","They have no timestamps"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why are confirmed blockchain records difficult to alter?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a liquidity pool?', '["A pool of assets used to support automated trading","A password list","A quiz database","A mining keyboard"]',0,75,'web3','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a liquidity pool?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a common Web3 security best practice?', '["Verify links and never share secret keys","Use the same password everywhere","Approve every popup","Post seed phrases publicly"]',0,40,'web3','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a common Web3 security best practice?');

-- Web2 and internet fundamentals
INSERT INTO `quiz_questions` SELECT NULL,'What does URL mean?', '["Uniform Resource Locator","User Route Login","Universal Record List","Unit Response Layer"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does URL mean?');
INSERT INTO `quiz_questions` SELECT NULL,'What does HTTP help transfer?', '["Web resources between clients and servers","Electricity","Paper mail","Audio through cables only"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does HTTP help transfer?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a browser used for?', '["Viewing and interacting with web content","Charging a battery","Mining every coin","Editing hardware"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a browser used for?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a search engine?', '["A service that helps find indexed information","A password manager only","A video cable","A keyboard shortcut"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a search engine?');
INSERT INTO `quiz_questions` SELECT NULL,'What does HTML primarily describe?', '["The structure of web pages","A database password","A network cable","A payment card"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does HTML primarily describe?');
INSERT INTO `quiz_questions` SELECT NULL,'What does CSS primarily control?', '["The presentation and styling of web pages","Server electricity","Database backups","Email delivery"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does CSS primarily control?');
INSERT INTO `quiz_questions` SELECT NULL,'What is JavaScript commonly used for on websites?', '["Interactive behavior and application logic","Printing circuit boards","Replacing the internet","Creating Wi-Fi signals"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is JavaScript commonly used for on websites?');
INSERT INTO `quiz_questions` SELECT NULL,'What is an API?', '["A defined way for software to communicate","A type of monitor","A secret key","A web image"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is an API?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a database?', '["An organized collection of data","A browser theme","A cable connector","A search result"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a database?');
INSERT INTO `quiz_questions` SELECT NULL,'What is cloud computing?', '["Using remote computing resources over a network","Storing files in the sky","A weather app only","A keyboard layout"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is cloud computing?');
INSERT INTO `quiz_questions` SELECT NULL,'What does DNS translate?', '["Domain names into network addresses","Images into videos","Passwords into usernames","Emails into coins"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does DNS translate?');
INSERT INTO `quiz_questions` SELECT NULL,'What is HTTPS intended to add?', '["Encrypted and authenticated web communication","More screen brightness","A larger keyboard","A faster mouse"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is HTTPS intended to add?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a cookie in web browsing?', '["Small data stored by a website in a browser","A baked snack sent by email","A server fan","A blockchain block"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a cookie in web browsing?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a cache?', '["Stored data kept to speed up later access","A secret wallet","A broken server","A type of email"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a cache?');
INSERT INTO `quiz_questions` SELECT NULL,'What is two-factor authentication?', '["Using two independent checks to sign in","Using two usernames","Opening two browsers","Having two email addresses"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is two-factor authentication?');
INSERT INTO `quiz_questions` SELECT NULL,'What is phishing?', '["A deceptive attempt to steal information","A video format","A database query","A network speed test"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is phishing?');
INSERT INTO `quiz_questions` SELECT NULL,'What does open source mean?', '["Source code is available under a license for inspection or use","No one can read the code","The app has no owner","The program runs without hardware"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does open source mean?');
INSERT INTO `quiz_questions` SELECT NULL,'What is version control used for?', '["Tracking changes to files and code","Increasing internet speed","Blocking all users","Compressing monitors"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is version control used for?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a server?', '["A computer or service that provides resources","A web password","A browser tab","A keyboard button"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a server?');
INSERT INTO `quiz_questions` SELECT NULL,'What does responsive design mean?', '["A page adapts to different screen sizes","A page replies to emails","A server talks aloud","A website has no images"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What does responsive design mean?');
INSERT INTO `quiz_questions` SELECT NULL,'What is an email attachment?', '["A file included with an email","A password hint","A browser extension","A server address"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is an email attachment?');
INSERT INTO `quiz_questions` SELECT NULL,'What is latency?', '["The delay before a response arrives","The amount of storage","The number of pixels","The length of a password"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is latency?');
INSERT INTO `quiz_questions` SELECT NULL,'What is bandwidth?', '["The capacity for data transfer over time","A browser bookmark","A password strength score","A type of camera"]',0,75,'web2','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is bandwidth?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a software bug?', '["A defect that causes unintended behavior","An insect in a laptop","A browser icon","A legal license"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a software bug?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a backup?', '["A separate copy used for recovery","A second monitor","A browser cookie","A public username"]',0,40,'web2','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a backup?');

-- Calculation questions
INSERT INTO `quiz_questions` SELECT NULL,'What is 7 + 8?', '["15","14","16","17"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 7 + 8?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 12 - 5?', '["7","6","8","9"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 12 - 5?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 6 × 4?', '["24","20","18","28"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 6 × 4?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 36 ÷ 6?', '["6","5","7","8"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 36 ÷ 6?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 15% of 200?', '["30","15","20","35"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 15% of 200?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 9²?', '["81","18","72","99"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 9²?');
INSERT INTO `quiz_questions` SELECT NULL,'What is the next number: 2, 4, 6, 8, ?', '["10","9","11","12"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is the next number: 2, 4, 6, 8, ?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 3/4 as a decimal?', '["0.75","0.25","0.5","1.25"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 3/4 as a decimal?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 2.5 + 1.75?', '["4.25","3.25","4.5","5.25"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 2.5 + 1.75?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 1000 - 375?', '["625","675","575","725"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 1000 - 375?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 11 × 11?', '["121","111","110","131"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 11 × 11?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 144 ÷ 12?', '["12","10","14","16"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 144 ÷ 12?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 25% of 80?', '["20","15","25","30"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 25% of 80?');
INSERT INTO `quiz_questions` SELECT NULL,'If x + 7 = 19, what is x?', '["12","10","11","13"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'If x + 7 = 19, what is x?');
INSERT INTO `quiz_questions` SELECT NULL,'If 3x = 21, what is x?', '["7","6","8","9"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'If 3x = 21, what is x?');
INSERT INTO `quiz_questions` SELECT NULL,'What is the average of 4, 8, and 12?', '["8","6","10","12"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is the average of 4, 8, and 12?');
INSERT INTO `quiz_questions` SELECT NULL,'A 50 point item rises by 20%. What is the new value?', '["60","55","70","65"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'A 50 point item rises by 20%. What is the new value?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 2³ + 4?', '["12","10","16","8"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 2³ + 4?');
INSERT INTO `quiz_questions` SELECT NULL,'What is the perimeter of a square with side 6?', '["24","12","36","18"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is the perimeter of a square with side 6?');
INSERT INTO `quiz_questions` SELECT NULL,'What is the area of a rectangle 5 by 9?', '["45","14","28","50"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is the area of a rectangle 5 by 9?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 1/5 of 100?', '["20","5","25","50"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 1/5 of 100?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 0.6 × 10?', '["6","0.06","60","1.6"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 0.6 × 10?');
INSERT INTO `quiz_questions` SELECT NULL,'A quiz gives 75 points and a bonus of 25. What is the total?', '["100","90","105","125"]',0,40,'calculation','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'A quiz gives 75 points and a bonus of 25. What is the total?');
INSERT INTO `quiz_questions` SELECT NULL,'What is 5!?', '["120","25","60","100"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is 5!?');
INSERT INTO `quiz_questions` SELECT NULL,'What is the remainder when 17 is divided by 5?', '["2","3","1","4"]',0,75,'calculation','medium',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is the remainder when 17 is divided by 5?');

-- Jokes and fun trivia
INSERT INTO `quiz_questions` SELECT NULL,'Why did the computer go to the doctor?', '["It had a virus","It wanted a haircut","It lost its shoes","It was hungry"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the computer go to the doctor?');
INSERT INTO `quiz_questions` SELECT NULL,'What do you call a bear with no teeth?', '["A gummy bear","A soft bear","A quiet bear","A sweet tooth"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do you call a bear with no teeth?');
INSERT INTO `quiz_questions` SELECT NULL,'Why was the math book sad?', '["It had too many problems","It lost a pen","It was too short","It disliked numbers"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why was the math book sad?');
INSERT INTO `quiz_questions` SELECT NULL,'What do clouds wear under their clothes?', '["Thunderwear","Rain socks","Sky jeans","Cloud shoes"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do clouds wear under their clothes?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the bicycle fall over?', '["It was two-tired","It lost a wheel","It was sleepy","It hit a wall"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the bicycle fall over?');
INSERT INTO `quiz_questions` SELECT NULL,'What has hands but cannot clap?', '["A clock","A tree","A shoe","A river"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What has hands but cannot clap?');
INSERT INTO `quiz_questions` SELECT NULL,'What has keys but cannot open locks?', '["A piano","A door","A map","A clock"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What has keys but cannot open locks?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the tomato blush?', '["It saw the salad dressing","It was spicy","It lost a game","It was cold"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the tomato blush?');
INSERT INTO `quiz_questions` SELECT NULL,'What kind of room has no doors or windows?', '["A mushroom","A bedroom","A classroom","A ballroom"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What kind of room has no doors or windows?');
INSERT INTO `quiz_questions` SELECT NULL,'Why can’t you trust stairs?', '["They are always up to something","They are too short","They move too fast","They have no steps"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why can’t you trust stairs?');
INSERT INTO `quiz_questions` SELECT NULL,'What did one wall say to the other wall?', '["I will meet you at the corner","Stop standing there","You are too tall","Open the door"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What did one wall say to the other wall?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the scarecrow win an award?', '["It was outstanding in its field","It was very scary","It could sing","It grew corn"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the scarecrow win an award?');
INSERT INTO `quiz_questions` SELECT NULL,'What do you call fake spaghetti?', '["An impasta","A pretend noodle","A false pasta","A noodle joke"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do you call fake spaghetti?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the cookie go to the hospital?', '["It felt crumby","It was too sweet","It lost a chip","It was baked"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the cookie go to the hospital?');
INSERT INTO `quiz_questions` SELECT NULL,'What do you call a sleeping bull?', '["A bulldozer","A calm cow","A nap bull","A quiet steer"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do you call a sleeping bull?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the golfer bring two pairs of trousers?', '["In case he got a hole in one","It was cold","He lost a bet","He liked pockets"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the golfer bring two pairs of trousers?');
INSERT INTO `quiz_questions` SELECT NULL,'What do you call a fish wearing a bowtie?', '["Sofishticated","A fancy fish","A dressed salmon","A party fish"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do you call a fish wearing a bowtie?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the banana go to the doctor?', '["It was not peeling well","It was yellow","It slipped","It was hungry"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the banana go to the doctor?');
INSERT INTO `quiz_questions` SELECT NULL,'What do you call a dog magician?', '["A Labracadabrador","A magic dog","A bark wizard","A spell puppy"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do you call a dog magician?');
INSERT INTO `quiz_questions` SELECT NULL,'Why was six afraid of seven?', '["Because seven ate nine","Because seven was loud","Because six was small","Because nine ran away"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why was six afraid of seven?');
INSERT INTO `quiz_questions` SELECT NULL,'What do you call a belt made of watches?', '["A waist of time","A clock belt","A time strap","A watch line"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do you call a belt made of watches?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the phone wear glasses?', '["It lost its contacts","It wanted style","It had a screen","It was reading"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the phone wear glasses?');
INSERT INTO `quiz_questions` SELECT NULL,'What do you call a group of musical whales?', '["An orca-stra","A sea band","A whale choir","A splash group"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What do you call a group of musical whales?');
INSERT INTO `quiz_questions` SELECT NULL,'Why did the robot take a break?', '["It needed to recharge","It got bored","It lost a wheel","It wanted lunch"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'Why did the robot take a break?');
INSERT INTO `quiz_questions` SELECT NULL,'What is a programmer’s favorite place to swim?', '["The data pool","The deep end","The code lake","The server sea"]',0,40,'jokes','easy',1 WHERE NOT EXISTS (SELECT 1 FROM quiz_questions WHERE question = 'What is a programmer’s favorite place to swim?');
